server:
  port: 8888

spring:

  datasource:
    username: root
    password: '%TGB6yhn'
    url: jdbc:mysql://192.168.4.97:3306/adms2?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,wall,logback
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      stat-view-servlet:
        login-username: admin
        login-password: admin

  thymeleaf:
    cache: false

  redis:
    host: 192.168.4.97
    port: 6379


mybatis:
  # 指定sql映射文件的位置
  mapper-locations: classpath:cn/ubot/app18/mapper/*.xml
  # 下划线映射驼峰规则
  configuration:
    map-underscore-to-camel-case: true
  # 别名
  type-aliases-package: cn.ubot.app18.pojo

logging:
  level:
    root: info
    cn.ubot.app18: debug


